### ISSUE TITLE
Epinano Variants frozen.  Not sure why.

### ISSUE THREAD

**Issue by niradsp** [novoalab/EpiNano#101]
Here are my commands.  I am running it two different ways.  First, using the reference genome:

`minimap2 --MD -t 50 -ax splice -k14 -uf /home/banskotan2/Reference/grch38/Homo_sapiens_HG38_GRCH38_104.fa combined_3.1.fastq.gz | samtools view -hbS -F 3844 - |samtools sort -@ 50 - combined_3.1.bam`

So I am mapping using the -ax splice command, and mapping to the reference genome.
The minimap2 version I am using is 2.14-r883.  

Next, I ran the variants program as follows:

`python /home/banskotan2/Tools/EpiNano/Epinano_Variants.py -n 10 -R /home/banskotan2/Reference/grch38/Homo_sapiens_HG38_GRCH38_104.fa -b /home/banskotan2/Projects/direct_rna_test/combined_3.1.bam.bam -s /home/banskotan2/Tools/EpiNano/misc/sam2tsv.jar --type g
`
The program appears to be frozen.  
Looking at the temporary directory, it seems to get frozen around chunks 230 to 250 for some reason.
That last chunk is chromosome 19.  It seems to me that for some reason it is not able to parse chromosomes starting with the number 2.

I am also running it differently by mapping it to a reference transcriptome:

`minimap2 --MD -t 50 -ax map-ont /home/banskotan2/Reference/grch38/Homo_sapiens.GRCh38.cdna.all.fa combined_3.1.fastq.gz | samtools view -hbS -F 3844 - |samtools sort -@ 50 - combined_3.1_transcriptome.bam
`

And the variants command:

`python /home/banskotan2/Tools/EpiNano/Epinano_Variants.py -n 10 -R /home/banskotan2/Reference/grch38/Homo_sapiens.GRCh38.cdna.all.fa -b /home/banskotan2/Projects/direct_rna_test/combined_3.1_transcriptome.bam.bam  -s /home/banskotan2/Tools/EpiNano/misc/sam2tsv.jar --type t
`

The command above seems to be running as far as I can tell.  It has been running for 16 hours or so.  Does it take this long?  The csv generated file is at 0 bytes, but I notice that the program is taking 5% (35 GB of memory).  
So, I think the transcriptome epinano_variants is working, but not the genome epinano_variants.

Also, I tried it on the test data.  It worked just fine.  
So any ideas why it is frozen when I run with --type g?

Thank  you in advance.

**Comment by niradsp** [comment]
Thank you @Huanle.
I sent you an email.  Please let me know if it works for you.

Thanks,
Nirad

**Comment by lvclark** [comment]
What was the solution?  I am having a similar problem with Epinano_Variants.py hanging.  The really perplexing part is that exactly where it hangs is different each time (generates a different number of .freq files).  It worked on six of my samples but not the other six.  Here is my script.  I can probably share files by Box if needed.  I am using the Docker image.

```
#!/bin/bash
#SBATCH -n 2
#SBATCH --mem=32G
#SBATCH -p hpcbio
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=lvclark@illinois.edu
#SBATCH -J epinano
#SBATCH --array=5-7,9-11
#SBATCH -D /home/groups/hpcbio/projects/redacted/redacted-oxfordRNA-2021Jun/src/slurm-out

# Script to retry epinano jobs that hung

cd /home/groups/hpcbio/projects/redacted/redacted-oxfordRNA-2021Jun/

Sample_ID=`head src/sample_list_May2022.txt -n $SLURM_ARRAY_TASK_ID | tail -n 1 | cut -f 1`
Cross=`head src/sample_list_May2022.txt -n $SLURM_ARRAY_TASK_ID | tail -n 1 | cut -f 4`

Guppy=results/guppy/2022-05-17_for_EpiNano
Date=2022-07-06
FlairDate=2022-06-14

Transcriptome=results/parent_transcriptomes/${FlairDate}/Cross${Cross}_transcriptome.fa

### Strict mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

### Modules
module purge
module load singularity/3.8.1

### Run Epinano
mkdir -p results/epinano/${Date}

singularity exec -e epi12_latest.sif python3 /usr/local/bin/EpiNano/Epinano_Variants.py \
  -R $Transcriptome --type t \
  -b results/minimap/${Date}/${Sample_ID}_all_sorted.bam \
  -s /usr/local/bin/EpiNano/misc/sam2tsv.jar -n $SLURM_NTASKS
```

**Comment by lvclark** [comment]
I also tried Epinano_Variants.dev.py (using a local copy, but executing it from the container) but got a "file not found" error with it.
