### ISSUE TITLE
Epinano Variants result

### ISSUE THREAD

**Issue by yuxinPenny** [novoalab/EpiNano#104]
The #Ref number from the Epinano Variants results seems weird

(base) yuxin@bio-sg-1:~$ head /home/share/yuxin/2021Fall/DATA/hm_tmp/HMEC_WT/bam/HMEC_WT_g.minus_strand.per.site.csv
#Ref,pos,base,strand,cov,q_mean,q_median,q_std,mis,ins,del
0,24738,C,-,1,11.00000,11.00000,0.00000,1.00000,0.00000,0.00000
0,24739,T,-,1,11.00000,11.00000,0.00000,1.00000,0.00000,0.00000
0,24740,G,-,1,12.00000,12.00000,0.00000,1.00000,0.00000,0.00000
0,24741,C,-,1,6.00000,6.00000,0.00000,1.00000,0.00000,0.00000
0,24742,T,-,1,6.00000,6.00000,0.00000,1.00000,0.00000,0.00000
0,24743,G,-,1,6.00000,6.00000,0.00000,1.00000,0.00000,0.00000
0,24744,A,-,1,12.00000,12.00000,0.00000,1.00000,0.00000,0.00000
0,24745,A,-,1,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000
0,24746,G,-,1,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000
(base) yuxin@bio-sg-1:~$ tail /home/share/yuxin/2021Fall/DATA/hm_tmp/HMEC_WT/bam/HMEC_WT_g.minus_strand.per.site.csv
60,134253345,G,-,4,12.00000,13.00000,4.58258,1.00000,0.00000,0.00000
60,134253346,G,-,4,14.75000,16.50000,7.29298,1.00000,0.00000,0.00000
60,134253347,C,-,4,8.75000,8.50000,3.03109,1.00000,0.00000,0.00000
60,134253348,T,-,4,7.75000,9.00000,3.69966,1.00000,0.00000,0.00000
60,134253349,G,-,4,7.25000,7.00000,1.78536,1.00000,0.00000,0.00000
60,134253350,T,-,4,6.00000,6.50000,1.87083,1.00000,0.00000,0.00000
60,134253351,G,-,2,5.00000,5.00000,0.00000,1.00000,0.00000,0.00000
60,134253352,C,-,1,6.00000,6.00000,0.00000,1.00000,0.00000,0.00000
60,134253353,A,-,1,4.00000,4.00000,0.00000,1.00000,0.00000,0.00000
60,134253354,G,-,1,5.00000,5.00000,0.00000,1.00000,0.00000,0.00000

The reference file I used seems normal:
(base) yuxin@bio-sg-1:~$ grep 'chr' /home/share/yuxin/2021Fall/DATA/hm_tmp/hg38.fa
>chr1
>chr10
>chr11
>chr11_KI270721v1_random
>chr12
>chr13
>chr14
>chr14_GL000009v2_random
>chr14_GL000225v1_random
>chr14_KI270722v1_random
>chr14_GL000194v1_random
>chr14_KI270723v1_random
>chr14_KI270724v1_random
>chr14_KI270725v1_random
>chr14_KI270726v1_random
>chr15

Can you give any clues?

**Comment by yuxinPenny** [comment]
I know where the problem is: I should use the sam2tsv in the EpiNano package file, rather than the one in my own directory.

**Comment by Huanle** [comment]
yup, you are right! @yuxinPenny
