### ISSUE TITLE
Remove test dataset from the relases

### ISSUE THREAD

**Issue by lucacozzuto** [novoalab/EpiNano#105]
Hi, I suggest placing the test dataset in another repository since it generates a compressed archive of 4.5 Gb.

**Comment by Huanle** [comment]
It's done. 
Please refer to https://github.com/novoalab/EpiNano/blob/master/test_data/make_predictions/README.md

**Comment by delocalizer** [comment]
The files are removed in the current version but remain in all git history so a clone of this repo is still huge. I suggest using `git filter-repo` to expunge them e.g. https://stackoverflow.com/a/66359970/6705037

**Comment by lucacozzuto** [comment]
You can also do a git clone --depth 1
