### ISSUE TITLE
Issue running EpiNano_Variants.py on docker

### ISSUE THREAD

**Issue by cindyeliang** [novoalab/EpiNano#106]
Hello, I am trying to run the EpiNano test files on the huanleliu/epi12 image on docker. When I initially tried to mount the image onto the directory on my local machine containing the test files (wt.bam, wt.bam.bai, ko.bam, ko.bam.bai, ref.fa, ref.fa.dict, ref.fa.fai), I became unable to view the test files. To get around this, I manually `cp`'d the test files to my docker container.

Command used to run Epinano_Variants.py:
`python EpiNano/Epinano_Variants.py -R ref.fa -b wt.bam -s sam2tsv.jar -T t -n 6`

Error:
```
  File "EpiNano/Epinano_Variants.py", line 51
    print (firstline.rstrip(), file=out_fh)
                                   ^
SyntaxError: invalid syntax
```
When I try to call the Epinano_Variants help dialogue, I get the following:
```
python EpiNano/Epinano_Variants.py -h
 
 File "EpiNano/Epinano_Variants.py", line 51
    print (firstline.rstrip(), file=out_fh)
                                   ^
SyntaxError: invalid syntax
```
When I specify using python 3, I do get the help dialogue outputted, but receive this error when running my command instead:

```
python3 EpiNano/Epinano_Variants.py -R ref.fa -b ko.bam -s sam2tsv.jar -T t -n 6
ko_TMP_ already exists, will overwrite it
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/bin/Python-3.6.3/Lib/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/bin/Python-3.6.3/Lib/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "EpiNano/Epinano_Variants.py", line 44, in split_tsv_for_per_site_var_freq
    head = next(tsv)
StopIteration
```

Any help would be appreciated. Thanks!

**Comment by Huanle** [comment]
Hi @cindyeliang ,
may i know which sam2tsv you are using?

**Comment by cindyeliang** [comment]
Hi @Huanle,
I was using the sam2tsv provided in the docker image. 

I was actually able to get Epinano_Variants to run on the test data already provided in the image's test data directory. However when I tried to run Epinano_DiffErr.R, I now get `Rscript: command not found`. Where is R located in this docker image?
Thanks!

**Comment by Huanle** [comment]
Hi @cindyeliang ,
R command is not included in the docker image.
