### ISSUE TITLE
Epinano_Current is really slow 

### ISSUE THREAD

**Issue by margot701** [novoalab/EpiNano#107]
Dear Epinano team, we are trying to use the Epinano 1.2  tool and we are struggling with the Epinano_Current step because it is incredibly slow. We are running with t=6. It is running for 2 days now and it is still in chunk 0 (each chunk has around 2GB data). When doing top we observe that processes are mainly in "S" status (see attachment). We also did top -H to explore the subprocesses and  only 4 to 8 are running while the other are consuming CPU though being in "S" status (see attachment). We are running in Intel i9-7920X computer with 12 core and 64 GB of ram. The data are in Samsung 860 SATA SSD. Is it suppose to be as slow or is there tools compatibility issue or anything else? for the fisrt step (Epinano_Variant) we used the transcriptome option using the ensembl reference. 
Thank you a lot by advance for your advice,
 
![printscreen top](https://user-images.githubusercontent.com/64224736/149118784-10b4669d-8d7c-4bb7-a5c1-92a0270cf923.png)
![printscreen top -H](https://user-images.githubusercontent.com/64224736/149118790-496fa5d8-dc84-492c-b1ce-9e5cf859043e.png)

**Comment by Huanle** [comment]
Hi @margot701 ,
sorry for the delayed response. 
have you finished it? 
I will look into the scripts and see if there is a way to improve it.
