### ISSUE TITLE
How to train the model with single feature, quality score

### ISSUE THREAD

**Issue by arthasking123** [novoalab/EpiNano#109]
I've read the 2019 paper's figure 2d, showing using single feature, the quality score can already train the model with high accuracy. However, I failed to find the procedure about how to train the model with this single feature. Could you please show me how to get the good accuracy with just one quality score feature? Also, in the download csv dataset, the quality values are all floats, however, if we transfer quality value directly from fastq files, the quality values are int. So how do you get the quality values? Thanks very much!

**Comment by Huanle** [comment]
Hi @arthasking123 ,
You can find some examples [here](https://github.com/novoalab/EpiNano/blob/master/test_data/train_models/train_test.sh).
