### ISSUE TITLE
Apply EpiNano on DNA data?

### ISSUE THREAD

**Issue by hukai916** [novoalab/EpiNano#113]
Hi developers,

Thanks for creating EpiNano! 

I have a quick question: is that possible to apply EpiNano-error for DNA modification prediction?
BTW, the https://github.com/enovoa/EpiNano/tree/master/test_data/train_models is empty.

Thanks,

--Kai

**Comment by Huanle** [comment]
Hi @hukai916 ,
To use it to process DNA data and to rely on the implemented machine learning algorithm, you will have to train models using DNA data. Alternatively, you can use it to generate feature tables and apply simple statistics such as fisher exact test and its likes to detect significant contrasts between samples and infer modifications. 

The reposistory has been migrated to https://github.com/novoalab/EpiNano. You will be find models there.
