### ISSUE TITLE
Migrate to conda?

### ISSUE THREAD

**Issue by katsikora** [novoalab/EpiNano#120]
Dear Team,

thanks for supplying this interesting and versatile tool. I was wondering if you would consider packaging it up for conda, which would make the installation of dependencies a far bit easier ?

Best regards,
Katarzyna

**Comment by enovoa** [comment]
Hi @katsikora - thanks for the suggestion. To avoid installing dependencies, you may use epinano 1.2. from the docker image included here (https://github.com/novoalab/EpiNano/tree/master/dockerfile) or epinano 1.1 from MasterOfPores nextflow workflow (https://github.com/biocorecrg/master_of_pores). Thanks!

**Comment by katsikora** [comment]
Hi Enovoa,

thanks for your suggestion!

Best,
Katarzyna
