### ISSUE TITLE
Error with EpiNano Predict

### ISSUE THREAD

**Issue by agouru55** [novoalab/EpiNano#121]
Hello! I am running into the following error when running Epinano_Predict with the pre-trained RRACH motif.:
```
Commad:  EpiNano/Epinano_Predict.py -m rrach.q3.mis3.del3.linear.dump -p alignment.sorted.chr1.plus_strand.per.site.5mer.csv -cl 8,13,23 --out_prefix rna_mod
Traceback (most recent call last):
  File "EpiNano/Epinano_Predict.py", line 73, in <module>
    mod_col = int (args['modification_status_column']) - 1 if args['modification_status_column'] else None
ValueError: invalid literal for int() with base 10: 'rrach.q3.mis3.del3.linear.dump'
```
The prior steps all seemed to work properly. How can I address this error? Thanks so much!

**Comment by enovoa** [comment]
Hi @agouru55  apologies for the slow reply - were you able to solve this issue? Otherwise please let me know. Thanks!

**Comment by Huanle** [comment]
Hi @agouru55 ,

It's my bad for this late reply.
The error msg indicates that the column number that you passed is not valid. 
Do you mind sharing a few lines of your input for me to help with debugging?
