### ISSUE TITLE
Is it possible to pass multiple features to Epinano_DiffErr ?

### ISSUE THREAD

**Issue by katsikora** [novoalab/EpiNano#122]
Dear Team,

thank you for providing this innovative tool.

I'm currently testing Epinano_DiffErr on the output of Epinano_sumErr run on 5-mers. My file contains columns named #Ref,pos,base,strand,cov,sum_err1,sum_err2,sum_err3,sum_err4,sum_err5 . Is it possible to pass all the five sum_err columns to DiffErr? I tried with a comma-separated list and this failed.

Would you have a suggestion of what would be the best way to go about it?

I'm using Epinano 1.2.0.

Best regards,

Katarzyna

**Comment by Huanle** [comment]
Hi @katsikora ,

Unfortunately, `Epinano_DiffErr.R` is designed to handle a single feature at one time. So you will have to run it repeatedly for multi-features or once for combined features. But i will think about enabling it to handle multiple features. 

Kind reminder: this script was made to analyze small RNAs. If you want to apply it to genome or very long transcripts, you'd better use it in a sliding window mode.
Hope this helps. 

Best,
Huanle
