### ISSUE TITLE
Epinano differr warning

### ISSUE THREAD

**Issue by rania-o** [novoalab/EpiNano#129]
Hello,
Each time I use Epinano_DiffErr.R, I get this warning :

```
1: ggrepel: 23 unlabeled data points (too many overlaps). Consider increasing max.overlaps 
2: ggrepel: 42 unlabeled data points (too many overlaps). Consider increasing max.overlaps
```

Please, can you tell me what this means ? and how to increase these overlaps ? and if I do, will it enhance the modif detection ?

Rania

**Comment by enovoa** [comment]
Hi @rania-o - have you tried the test data of the repo? Thanks

**Comment by rania-o** [comment]
Hi @enovoa 
Thank you for your fast reply.
No I didn't use it with the test data of the repo, but I used with other test data and it worked well without the warning.

**Comment by enovoa** [comment]
Please share reproducible command line with input data to be able to reproduce the error, because we have never encountered it. Thank you!

**Comment by Huanle** [comment]
> Hi @enovoa Thank you for your fast reply. No I didn't use it with the test data of the repo, but I used with other test data and it worked well without the warning.

Hi @rania-o ,

Have you sorted it out? Can you share your input data?

Best,
Huanle

**Comment by rania-o** [comment]
Hi @Huanle , @enovoa 

Sorry for my late reply.
No, I didn't sorted it out, but as I already mentioned I do get results with the warning.
Our data is too big to transfer it to you.
On the other hand, I got the warning also by testing the data provided by Drummer in their [github,](https://github.com/DepledgeLab/DRUMMER/tree/master/TESTDATA) here is the command I used:

`Rscript /home/rania.ouazahrou/softs/EpiNano/Epinano_DiffErr.R -k exome.Ad5.UNMOD.plus_strand.per.site.csv -w exome.Ad5.MOD.plus_strand.per.site.csv -o epinano_results_001_deviance_4_t -f sum_err -p -t 4 -d 0.01`


You can find the *.csv files of the command Epinano_Variants.py.

Thank you,
Rania

**Comment by Huanle** [comment]
Hi @rania-o ,

It is an alarming emitted by ggrepel, which repels away texts, labels and data points.
But when there are too many overlaps between the above mentioned elements, it relseases the warning message you have seen. 

It wont affect the analysis. 

Hope this helps. 

Cheers - Huanle
