### ISSUE TITLE
No module named 'sklearn.svm.classes'

### ISSUE THREAD

**Issue by matjack2000** [novoalab/EpiNano#140]
Hi, 
I'm trying to use Epinano_Predict : 
'Python /home/labct/EpiNano/Epinano_Predict.py --model /home/labct/EpiNano/models/rrach.q3.mis3.del3.linear.dump --predict reads-ref.sorted.plus_strand.per.site.5mer.csv --columns 8,13,23 --out_prefix wt'
And I have this error : 
ModuleNotFoundError: No module named 'sklearn.svm.classes'

I'm using the latest version of Scikit-learn (1.22) and I tried with an older one (0.24.2), without succes. 
I'm on Ubuntu.
Thanks in advance for your answer.

**Comment by DelphIONe** [comment]
Same problem here.

Thanks for your answer!

**Comment by Huanle** [comment]
Hi @DelphIONe @matjack2000 

Can you install the required packages listed [here](https://github.com/novoalab/EpiNano#pre-requisites) and try again?
Best,
Huanle

**Comment by enovoa** [comment]
Closing this issue as I assume it was resolved installing the dependencies. Thanks!
