### ISSUE TITLE
Error running slide variants

### ISSUE THREAD

**Issue by doshirLV** [novoalab/EpiNano#144]
### Command:
`python /path/to/EpiNano/misc/Slide_Variants.py sample.minus_strand.per.site.csv 5`
### Error:
`Traceback (most recent call last):`
`  File "/path/to/EpiNano/misc/Slide_Variants.py", line 20, in <module>`
`    slide_per_site_var(per_site_var, kmer_len)`
`  File "/path/to/EpiNano/misc/../epinano_modules.py", line 861, in slide_per_site_var`
`    tmpfh = open (out_tmp,'r')`
`FileNotFoundError: [Errno 2] No such file or directory: 'sample.minus_strand.per_site_var.5mer.tmp'`
### Notes:
- When I open the `sample.minus_strand.per_site_var.5mer.csv` file, which should be the output of the `Slide_Variants.py` function, it is empty with only a header. 
- I could run it perfectly fine with the plus strand of the same sample.
- Also, when I observe the files as the script is running, a `sample.minus_strand.per_site_var.5mer.tmp` file definitely gets created in the directory, but something happens where it cannot be found when the script finishes.
- Any idea what might be causing this?

Thank you for the help,
Raj

**Comment by Huanle** [comment]
Hi @doshirLV 

I have requested to commit changes to the repo.  The new script will be available very soon. Once you can clone it, give it a go and hit me up whenever you run into any problems. 

Best,
Huanle

**Comment by enovoa** [comment]
Can you please test the new slide_variants script from EpiNano 1.2.3? Thanks

**Comment by doshirLV** [comment]
Thank you for the new slide_variants script and for providing feedback on the non-consecutive-sites file @Huanle.
Feel free to close this issue, I do not have any problems with processing the plus/minus strand or the speed of this command.
