### ISSUE TITLE
EpiNano --type g

### ISSUE THREAD

**Issue by GregorD96** [novoalab/EpiNano#146]
Hello,
I enocuntered a potential bug in EpiNano:

If run with option --type t (default), only the object with the positive strand reads will be analysed. If --type g, both objects will be analysed with EpiNano. Issue is that if any of these objects are empty - EpiNano will hang and therefore, the job will fail after the requested time passes.

Best,

Gregor

**Comment by enovoa** [comment]
Fixed in latest update v1.2.4 [https://github.com/novoalab/EpiNano/commit/efb88021599783c6c420ec368a7f67a433fd246c]
